import type { Metadata } from "next";
import { Toaster } from "react-hot-toast";
import { GeistSans } from "geist/font/sans"
import "./globals.css";
import ClientProvider from "@/components/ClientProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <body
className={GeistSans.className}
      >
        <ClientProvider>
        {children}
        </ClientProvider>
         <Toaster
          position="top-right"
          toastOptions={{
            duration: 5000,
            style: {
              background: "rgba(10, 15, 26, 0.85)",        // dark glass
              backdropFilter: "blur(8px)",
              color: "#e0faff",                            // cyan tint
              border: "1px solid rgba(0, 212, 255, 0.35)", // neon border
              boxShadow: "0 0 20px rgba(0, 212, 255, 0.25)",
              padding: "12px 16px",
              fontSize: "15px",
              borderRadius: "10px",
            },

            // success variant
            success: {
              style: {
                border: "1px solid rgba(34, 211, 238, 0.5)",
                color: "#c7faff",
                background: "rgba(8, 40, 48, 0.85)",
              },
            },

            // error variant
            error: {
              style: {
                border: "1px solid rgba(255, 72, 72, 0.45)",
                color: "#ffd5d5",
                background: "rgba(48, 8, 8, 0.85)",
                boxShadow: "0 0 20px rgba(255, 72, 72, 0.25)",
              },
            },
          }}
        />

      </body>
    </html>
  );
}
