import type { Metadata } from "next";
import { Toaster } from "react-hot-toast";
import { GeistSans } from "geist/font/sans"
import "./globals.css";




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <body
className={GeistSans.className}
      >
        {children}
        <Toaster position="top-right" />
      </body>
    </html>
  );
}
